#!/bin/bash

# variables
CONTAINER_NAME=smw-platformio-dev
CONTAINER_DIR=containers/PIO_Container/

# go to where dockerfile is
pushd ${CONTAINER_DIR}

# build container
docker build -t ${CONTAINER_NAME} .

# go back to root
popd

# run smartwatch dev and build container
docker run --rm -it -v $(pwd)/:/workspace \
    -w /workspace \
    --device=/dev/ttyUSB0:/dev/ttyUSB0 \
    ${CONTAINER_NAME}